Chest:
  a:
    Item:
    - '54:0;100'
    - '12:0;50'
  b:
    Item:
    - '1:0;100'
    - '2:0;50'
  c:
    Item:
    - '1:0;100'
    - '2:0;50'
  d:
    Item:
    - '1:0;100'
    - '2:0;50'